export const DEAD_LETTER_ERROR_CODE = {
  NOT_FOUND: 'DEAD_LETTER_NOT_FOUND',
  REPLAY_REQUIRES_DEAD_FAILED: 'DEAD_LETTER_REPLAY_REQUIRES_DEAD_FAILED',
  REPLAY_ALREADY_EXISTS: 'WRITEBACK_REPLAY_ALREADY_EXISTS',
  ALREADY_ACKNOWLEDGED: 'DEAD_LETTER_ALREADY_ACKNOWLEDGED'
} as const;

export type DeadLetterErrorCode =
  (typeof DEAD_LETTER_ERROR_CODE)[keyof typeof DEAD_LETTER_ERROR_CODE];
